ktor:
  deployment:
    port: 8080
  application:
    modules:
      - net.kalbskinder.HttpKt.configureHttp
      - net.kalbskinder.SerializationKt.configureSerialization
      - net.kalbskinder.RoutingKt.configureRouting
