ktor:
  deployment:
    port: 8080
  application:
    modules:
      - net.kalbskinder.ApplicationKt.module

pluginwizard:
  cors:
    allowedHosts:
      - "localhost:5173"
      - "editor.kalbskinder.net"
  build:
    tempDir: "/tmp/pluginwizard-builds"
    timeoutSeconds: 30
